/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Brian54
 */
public class AltaPacienteRoom extends javax.swing.JFrame {

    /**
     * Creates new form AltaPacienteRoom
     */
    public AltaPacienteRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtAdmitDate = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtBloodGroup = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtDisease = new javax.swing.JTextField();
        txtDoctorID = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        txtRoomNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtDischargeDate = new javax.swing.JTextField();
        btnDatosPaciente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnObtenerDatos = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblMinimiza = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descarga de Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("ID del paciente ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Nombre del paciente ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 69, -1, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setText("Grupo sanguíneo ");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 145, -1, -1));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setText("Observaciones ");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 409, -1, -1));

        txtPatientID.setEditable(false);
        txtPatientID.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 27, 89, 21));

        txtPatientName.setEditable(false);
        txtPatientName.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 66, 193, -1));

        txtAdmitDate.setEditable(false);
        txtAdmitDate.setBackground(new java.awt.Color(102, 255, 255));
        txtAdmitDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel3.add(txtAdmitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 218, 120, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setText("Genero");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 107, -1, -1));

        jLabel30.setText("(YYYY-MM-DD)");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 221, -1, -1));

        txtGender.setEditable(false);
        txtGender.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 104, 194, -1));

        txtBloodGroup.setEditable(false);
        txtBloodGroup.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 142, 194, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setText("Enfermedad ");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 180, -1, -1));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel32.setText("Fecha de admisión ");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 221, -1, -1));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel33.setText("no. Habitación  ");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 259, -1, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel34.setText("ID Doctor ");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 297, -1, -1));

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel35.setText("Nombre del doctor ");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 336, -1, -1));

        txtDisease.setEditable(false);
        txtDisease.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 180, 194, -1));

        txtDoctorID.setEditable(false);
        txtDoctorID.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 294, 75, 21));

        txtDoctorName.setEditable(false);
        txtDoctorName.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 333, 194, -1));

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        jScrollPane3.setViewportView(txtRemarks);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 409, 190, 80));

        txtRoomNo.setEditable(false);
        txtRoomNo.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(txtRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 256, 120, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de alta ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 374, -1, -1));

        jLabel36.setText("(YYYY-MM-DD)");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 374, -1, -1));
        jPanel3.add(txtDischargeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 371, 120, -1));

        btnDatosPaciente.setText("<");
        jPanel3.add(btnDatosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 23, 87, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 500));
        jPanel3.getAccessibleContext().setAccessibleName("Descarga de Paciente");

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(102, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(java.awt.Color.lightGray);
        btnGuardar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        btnNuevo.setBackground(java.awt.Color.lightGray);
        btnNuevo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        btnBorrar.setBackground(java.awt.Color.lightGray);
        btnBorrar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));

        btnObtenerDatos.setBackground(java.awt.Color.lightGray);
        btnObtenerDatos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnObtenerDatos.setText("Listar");
        btnObtenerDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(btnObtenerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        btnActualizar.setBackground(java.awt.Color.lightGray);
        btnActualizar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 130, 210));

        lblMinimiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimiza.png"))); // NOI18N
        jPanel1.add(lblMinimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Alta Paciente.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnDatosPaciente;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnObtenerDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblMinimiza;
    public javax.swing.JFormattedTextField txtAdmitDate;
    public javax.swing.JTextField txtBloodGroup;
    public javax.swing.JTextField txtDischargeDate;
    public javax.swing.JTextField txtDisease;
    public javax.swing.JTextField txtDoctorID;
    public javax.swing.JTextField txtDoctorName;
    public javax.swing.JTextField txtGender;
    public javax.swing.JTextField txtPatientID;
    public javax.swing.JTextField txtPatientName;
    public javax.swing.JTextArea txtRemarks;
    public javax.swing.JTextField txtRoomNo;
    // End of variables declaration//GEN-END:variables
}
