
package vista;

/**
 *
 * @author Brian54
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMNuevoUsuario = new javax.swing.JMenuItem();
        JMCambiarContraseña = new javax.swing.JMenuItem();
        JMDetalleRegistro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMPacienteRegistro = new javax.swing.JMenuItem();
        JMPacienteServicio = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        JMEntradaDoctores = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        JMAgregarHabitacion = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        JMAdministrarHabitacion = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        JMDescargaHabitacion = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        JMFacturaHabitacion = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimiza.png"))); // NOI18N
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 20, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hospital.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 550));

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 51));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu1.setText("USUARIO");
        jMenu1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N

        JMNuevoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        JMNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JMNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/USER.png"))); // NOI18N
        JMNuevoUsuario.setText("Nuevo Usuario");
        jMenu1.add(JMNuevoUsuario);

        JMCambiarContraseña.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        JMCambiarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JMCambiarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/passC.png"))); // NOI18N
        JMCambiarContraseña.setText("Cambiar Contraseña");
        jMenu1.add(JMCambiarContraseña);

        JMDetalleRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        JMDetalleRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JMDetalleRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        JMDetalleRegistro.setText("Detalle de Registro");
        jMenu1.add(JMDetalleRegistro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("PACIENTE");
        jMenu2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N

        JMPacienteRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        JMPacienteRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JMPacienteRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paciente.png"))); // NOI18N
        JMPacienteRegistro.setText("Registro");
        jMenu2.add(JMPacienteRegistro);

        JMPacienteServicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMPacienteServicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JMPacienteServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/servicio.png"))); // NOI18N
        JMPacienteServicio.setText("Servicios");
        jMenu2.add(JMPacienteServicio);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("DOCTORES");
        jMenu7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N

        JMEntradaDoctores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        JMEntradaDoctores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JMEntradaDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entradaDoc.png"))); // NOI18N
        JMEntradaDoctores.setText("Entrada");
        jMenu7.add(JMEntradaDoctores);

        jMenuBar1.add(jMenu7);

        jMenu10.setText("HABITACIONES");
        jMenu10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuartoH.png"))); // NOI18N
        jMenu12.setText("Agregar Habitación");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JMAgregarHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuartoH.png"))); // NOI18N
        JMAgregarHabitacion.setText("Habitación");
        jMenu12.add(JMAgregarHabitacion);

        jMenu10.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adminH.png"))); // NOI18N
        jMenu13.setText("Admin");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JMAdministrarHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuartoH.png"))); // NOI18N
        JMAdministrarHabitacion.setText("Habitación");
        jMenu13.add(JMAdministrarHabitacion);

        jMenu10.add(jMenu13);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descargaH.png"))); // NOI18N
        jMenu14.setText("Descarga");
        jMenu14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JMDescargaHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuartoH.png"))); // NOI18N
        JMDescargaHabitacion.setText("Room");
        jMenu14.add(JMDescargaHabitacion);

        jMenu10.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturaH.png"))); // NOI18N
        jMenu15.setText("Facturación");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JMFacturaHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuartoH.png"))); // NOI18N
        JMFacturaHabitacion.setText("Habitacion");
        jMenu15.add(JMFacturaHabitacion);

        jMenu10.add(jMenu15);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("AYUDA");
        jMenu11.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acercaH.png"))); // NOI18N
        jMenuItem11.setText("Acerca");
        jMenu11.add(jMenuItem11);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem JMAdministrarHabitacion;
    public javax.swing.JMenuItem JMAgregarHabitacion;
    public javax.swing.JMenuItem JMCambiarContraseña;
    public javax.swing.JMenuItem JMDescargaHabitacion;
    public javax.swing.JMenuItem JMDetalleRegistro;
    public javax.swing.JMenuItem JMEntradaDoctores;
    public javax.swing.JMenuItem JMFacturaHabitacion;
    public javax.swing.JMenuItem JMNuevoUsuario;
    public javax.swing.JMenuItem JMPacienteRegistro;
    public javax.swing.JMenuItem JMPacienteServicio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu10;
    public javax.swing.JMenu jMenu11;
    public javax.swing.JMenu jMenu12;
    public javax.swing.JMenu jMenu13;
    public javax.swing.JMenu jMenu14;
    public javax.swing.JMenu jMenu15;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    public javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables
}
