/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Brian54
 */
public class RegistroDoctor extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDoctor
     */
    public RegistroDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdDoctor = new javax.swing.JTextField();
        txtNameDoctor = new javax.swing.JTextField();
        txtFatherDoctor = new javax.swing.JTextField();
        txtEmailDoctor = new javax.swing.JTextField();
        txtNumberDoctor = new javax.swing.JTextField();
        txtAddressDoctor = new javax.swing.JTextField();
        txtQualificationsDoctor = new javax.swing.JTextField();
        txtFechaDoctor = new javax.swing.JTextField();
        cbxGenero = new javax.swing.JComboBox();
        cbxGrupo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnObtenerDatos = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Doctor"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Identificación del doctor ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 37, -1, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Nombre completo ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 79, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del Padre ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 121, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Identificación de correo ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 163, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("No Contacto  ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 205, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Dirección ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 239, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Calificaciones ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 281, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Genero");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 326, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Grupo sanguíneo ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("Fecha de inscripción ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 394, -1, -1));

        txtIdDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtIdDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtIdDoctor.setBorder(null);
        jPanel3.add(txtIdDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 170, -1));

        txtNameDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtNameDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNameDoctor.setBorder(null);
        jPanel3.add(txtNameDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        txtFatherDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtFatherDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtFatherDoctor.setBorder(null);
        jPanel3.add(txtFatherDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, -1));

        txtEmailDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtEmailDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtEmailDoctor.setBorder(null);
        jPanel3.add(txtEmailDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, -1));

        txtNumberDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtNumberDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNumberDoctor.setBorder(null);
        jPanel3.add(txtNumberDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        txtAddressDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtAddressDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtAddressDoctor.setBorder(null);
        jPanel3.add(txtAddressDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, -1));

        txtQualificationsDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtQualificationsDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtQualificationsDoctor.setBorder(null);
        jPanel3.add(txtQualificationsDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 170, -1));

        txtFechaDoctor.setBackground(new java.awt.Color(102, 255, 255));
        txtFechaDoctor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtFechaDoctor.setBorder(null);
        txtFechaDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDoctorActionPerformed(evt);
            }
        });
        jPanel3.add(txtFechaDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 80, -1));

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        jPanel3.add(cbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 328, -1, -1));

        cbxGrupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jPanel3.add(cbxGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 362, -1, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setText("YYYY-MM-DD");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 170, -1));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, -1));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, -1));

        jSeparator8.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 80, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 430));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("Registro Doctor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(102, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(java.awt.Color.lightGray);
        btnGuardar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        btnNuevo.setBackground(java.awt.Color.lightGray);
        btnNuevo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        btnBorrar.setBackground(java.awt.Color.lightGray);
        btnBorrar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        btnObtenerDatos.setBackground(java.awt.Color.lightGray);
        btnObtenerDatos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnObtenerDatos.setText("Obtener datos");
        btnObtenerDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(btnObtenerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 30));

        btnActualizar.setBackground(java.awt.Color.lightGray);
        btnActualizar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 120, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Doc.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 519, 531));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnObtenerDatos;
    public javax.swing.JComboBox cbxGenero;
    public javax.swing.JComboBox cbxGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField txtAddressDoctor;
    public javax.swing.JTextField txtEmailDoctor;
    public javax.swing.JTextField txtFatherDoctor;
    public javax.swing.JTextField txtFechaDoctor;
    public javax.swing.JTextField txtIdDoctor;
    public javax.swing.JTextField txtNameDoctor;
    public javax.swing.JTextField txtNumberDoctor;
    public javax.swing.JTextField txtQualificationsDoctor;
    // End of variables declaration//GEN-END:variables
}
